// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNHUvwuavR8yh6memEBHYZQ9w1RaULp0I',
    appId: '1:625478574980:web:10a505f35dd2596d4eb3d1',
    messagingSenderId: '625478574980',
    projectId: 'credit-scoring-22b28',
    authDomain: 'credit-scoring-22b28.firebaseapp.com',
    storageBucket: 'credit-scoring-22b28.firebasestorage.app',
    measurementId: 'G-98XM0V9NE9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMJblAfBQQYv38e0zniwRMxTMHfvQZnRw',
    appId: '1:625478574980:android:1b1e2bd6d61ce48f4eb3d1',
    messagingSenderId: '625478574980',
    projectId: 'credit-scoring-22b28',
    storageBucket: 'credit-scoring-22b28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcRpUa6sDfy98WknWvtyMOIKB-1ZMbMIg',
    appId: '1:625478574980:ios:eaf6d9375e7a861a4eb3d1',
    messagingSenderId: '625478574980',
    projectId: 'credit-scoring-22b28',
    storageBucket: 'credit-scoring-22b28.firebasestorage.app',
    iosClientId: '625478574980-ckvatpsk0cslenk7ks7uao3m11i64123.apps.googleusercontent.com',
    iosBundleId: 'com.example.creditscoring',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcRpUa6sDfy98WknWvtyMOIKB-1ZMbMIg',
    appId: '1:625478574980:ios:eaf6d9375e7a861a4eb3d1',
    messagingSenderId: '625478574980',
    projectId: 'credit-scoring-22b28',
    storageBucket: 'credit-scoring-22b28.firebasestorage.app',
    iosClientId: '625478574980-ckvatpsk0cslenk7ks7uao3m11i64123.apps.googleusercontent.com',
    iosBundleId: 'com.example.creditscoring',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNHUvwuavR8yh6memEBHYZQ9w1RaULp0I',
    appId: '1:625478574980:web:a7c1d224c78176984eb3d1',
    messagingSenderId: '625478574980',
    projectId: 'credit-scoring-22b28',
    authDomain: 'credit-scoring-22b28.firebaseapp.com',
    storageBucket: 'credit-scoring-22b28.firebasestorage.app',
    measurementId: 'G-XNFR18LBWX',
  );

}