import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:intl/intl.dart';
import '../models/notification_model.dart';

/// Service for managing real-time notifications
class NotificationService {
  final _currencyFormat = NumberFormat.currency(locale: 'vi_VN', symbol: '₫');

  /// Create notification when loan application is processed
  Future<void> createLoanNotification({
    required String userId,
    required String applicationId,
    required bool approved,
    required int creditScore,
    required double loanAmount,
  }) async {
    try {
      String title;
      String body;
      String type;

      if (approved) {
        title = 'Loan Approved';
        body =
            'Your loan of ${_currencyFormat.format(loanAmount)} has been approved';
        type = 'loan_approved';
      } else {
        title = 'Loan Application Update';
        body = 'Your loan application needs review';
        type = 'loan_rejected';
      }

      final notification = NotificationModel(
        id: '', // Will be auto-generated by Firestore
        userId: userId,
        applicationId: applicationId,
        type: type,
        title: title,
        body: body,
        data: {
          'creditScore': creditScore,
          'loanAmount': loanAmount,
          'approved': approved,
        },
        isRead: false,
        createdAt: DateTime.now(),
      );

      await FirebaseFirestore.instance
          .collection('notifications')
          .add(notification.toFirestore());

      print('[NotificationService] Created notification: $title');
    } catch (e) {
      print('[NotificationService] Error creating notification: $e');
      // Don't throw - notification creation should not break the main flow
    }
  }

  /// Create credit score update notification
  Future<void> createCreditScoreNotification({
    required String userId,
    required int oldScore,
    required int newScore,
  }) async {
    try {
      final difference = newScore - oldScore;
      final title = 'Credit Score Updated';
      final body = difference > 0
          ? 'Your score increased by $difference points'
          : 'Your score decreased by ${difference.abs()} points';

      final notification = NotificationModel(
        id: '',
        userId: userId,
        type: 'credit_score_updated',
        title: title,
        body: body,
        data: {
          'oldScore': oldScore,
          'newScore': newScore,
          'difference': difference,
        },
        isRead: false,
        createdAt: DateTime.now(),
      );

      await FirebaseFirestore.instance
          .collection('notifications')
          .add(notification.toFirestore());

      print('[NotificationService] Created credit score notification');
    } catch (e) {
      print(
        '[NotificationService] Error creating credit score notification: $e',
      );
    }
  }

  /// Get notifications stream for a user (real-time)
  Stream<List<NotificationModel>> getNotificationsStream(String userId) {
    return FirebaseFirestore.instance
        .collection('notifications')
        .where('userId', isEqualTo: userId)
        .snapshots()
        .map((snapshot) {
          // Sort in memory instead of using orderBy to avoid index requirement
          final notifications = snapshot.docs
              .map((doc) => NotificationModel.fromFirestore(doc))
              .toList();

          // Sort by createdAt descending (newest first)
          notifications.sort((a, b) => b.createdAt.compareTo(a.createdAt));

          // Limit to last 50 notifications
          return notifications.take(50).toList();
        });
  }

  /// Get unread count stream (real-time)
  Stream<int> getUnreadCountStream(String userId) {
    return FirebaseFirestore.instance
        .collection('notifications')
        .where('userId', isEqualTo: userId)
        .where('isRead', isEqualTo: false)
        .snapshots()
        .map((snapshot) => snapshot.docs.length);
  }

  /// Mark notification as read
  Future<void> markAsRead(String notificationId) async {
    try {
      await FirebaseFirestore.instance
          .collection('notifications')
          .doc(notificationId)
          .update({'isRead': true});
    } catch (e) {
      print('[NotificationService] Error marking notification as read: $e');
      rethrow;
    }
  }

  /// Mark all notifications as read for a user
  Future<void> markAllAsRead(String userId) async {
    try {
      final batch = FirebaseFirestore.instance.batch();
      final snapshot = await FirebaseFirestore.instance
          .collection('notifications')
          .where('userId', isEqualTo: userId)
          .where('isRead', isEqualTo: false)
          .get();

      for (var doc in snapshot.docs) {
        batch.update(doc.reference, {'isRead': true});
      }

      await batch.commit();
      print('[NotificationService] Marked all notifications as read');
    } catch (e) {
      print('[NotificationService] Error marking all as read: $e');
      rethrow;
    }
  }

  /// Delete notification
  Future<void> deleteNotification(String notificationId) async {
    try {
      await FirebaseFirestore.instance
          .collection('notifications')
          .doc(notificationId)
          .delete();
    } catch (e) {
      print('[NotificationService] Error deleting notification: $e');
      rethrow;
    }
  }

  /// Delete all notifications for a user
  Future<void> deleteAllNotifications(String userId) async {
    try {
      final batch = FirebaseFirestore.instance.batch();
      final snapshot = await FirebaseFirestore.instance
          .collection('notifications')
          .where('userId', isEqualTo: userId)
          .get();

      for (var doc in snapshot.docs) {
        batch.delete(doc.reference);
      }

      await batch.commit();
      print('[NotificationService] Deleted all notifications');
    } catch (e) {
      print('[NotificationService] Error deleting all notifications: $e');
      rethrow;
    }
  }

  /// Get recent notifications (non-stream, for one-time fetch)
  Future<List<NotificationModel>> getRecentNotifications(
    String userId, {
    int limit = 10,
  }) async {
    try {
      final snapshot = await FirebaseFirestore.instance
          .collection('notifications')
          .where('userId', isEqualTo: userId)
          .orderBy('createdAt', descending: true)
          .limit(limit)
          .get();

      return snapshot.docs
          .map((doc) => NotificationModel.fromFirestore(doc))
          .toList();
    } catch (e) {
      print('[NotificationService] Error getting recent notifications: $e');
      return [];
    }
  }
}
